[package]
name = "cargo-fel4"
version = "0.0.1"
publish = false

[dependencies]
cargo_metadata = "0.5"
cmake_config = { version = "*", path = "cmake_config" }
colored = "1.6"
fel4-config = { git = "ssh://github.com/PolySync/fel4-config.git", branch = "master" }
log = "0.4"
structopt = "0.2"
